name: Call WebService Weekly

on:
  schedule:
    - cron: '5 10 * * 2'  # Entspricht 11:10 Wien-Zeit im Winter

jobs:
  call-webservice:
    runs-on: ubuntu-latest
    steps:
      - name: Set timezone to Vienna
        run: sudo timedatectl set-timezone Europe/Vienna

      - name: Call WebService URL
        run: |
          # Führe den Aufruf mit curl durch
          curl --fail -X GET "https://telbot-7bag.onrender.com/remindme"
