name: Call WebService Weekly

on:
  schedule:
    # Jeden Samstag um 10:30 UTC ausführen
    - cron: '55 9 * * 2'  # ⚠️ Cron-Syntax: 6 = Samstag (0-6, Sonntag=0)

jobs:
  call-webservice:
    runs-on: ubuntu-latest
    steps:
      - name: Call WebService URL (triggers Telegram notification)
        run: |
          # Führe den Aufruf mit curl durch
          curl -X GET "https://telbot-7bag.onrender.com"
          
          # Optionale Statusprüfung (falls benötigt)
          if [ $? -ne 0 ]; then
            echo "Fehler beim Aufruf des WebServices!"
            exit 1
          fi
